# 幫我使用 sqplite 指令完成要求的功能
# 我有 3 個 已經建立完成的table 分別是 oil_price gold_price fx_rate
# SELECT 
# CREATE VIEW hw_2 AS SELECT  FX_RATE.DAY, FX_RATE.RATE AS FX_RATE, OIL_PRICE.PRICE AS OIL_PRICE, GOLD_PRICE.PRICE AS GOLD_PRICE FROM FX_RATE LEFT JOIN OIL_PRICE ON FX_RATE.DAY = OIL_PRICE.DAY LEFT JOIN GOLD_PRICE ON FX_RATE.DAY = GOLD_PRICE.DAY;
# 但是 view hw_2 有一個問題，就是有些日期沒有資料 oil_price  會是 NULL，請幫我填補這些缺失的資料
# 補法是用前一天的資料補上去
# 舉例來說，假設 2020-01-02 的 oil_price 是 NULL，那就用 2020-01-01 的資料補上去
# 利用 sqlite 指令幫我完成這個功能
# 輸出結果是一個新的 view hw4_tritb
# 請直接告訴我你的 sqlite 指令

# CREATE VIEW hw4_tritb AS SELECT  FX_RATE.DAY, FX_RATE.RATE AS FX_RATE, OIL_PRICE.PRICE AS OIL_PRICE, GOLD_PRICE.PRICE AS GOLD_PRICE FROM FX_RATE LEFT JOIN OIL_PRICE ON FX_RATE.DAY = OIL_PRICE.DAY LEFT JOIN GOLD_PRICE ON FX_RATE.DAY = GOLD_PRICE.DAY;

# CREATE VIEW hw4_tritb AS SELECT  FX_RATE.DAY, FX_RATE.RATE AS FX_RATE, COALESCE(OIL_PRICE.PRICE, (SELECT PRICE FROM OIL_PRICE WHERE DAY < FX_RATE.DAY ORDER BY DAY DESC LIMIT 1)) AS OIL_PRICE, GOLD_PRICE.PRICE AS GOLD_PRICE FROM FX_RATE LEFT JOIN OIL_PRICE ON FX_RATE.DAY = OIL_PRICE.DAY LEFT JOIN GOLD_PRICE ON FX_RATE.DAY = GOLD_PRICE.DAY;

   
    